/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

/// <summary>
/// You can define enums, which are just 32 bit integers. Values are optional
/// and start at 1 if not supplied, C style again.
/// </summary>
public enum DataTypeP
{
  STRING = 0,
  INTEGER = 1,
  DATETIME = 2,
  BOOLEAN = 3,
}
