/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

public partial class RemotePEPService {
  public interface Iface {
    bool isAuthorized(SubjectP subject, ObjectP object, ActionP action, EnvironmentP environment);
    #if SILVERLIGHT
    IAsyncResult Begin_isAuthorized(AsyncCallback callback, object state, SubjectP subject, ObjectP object, ActionP action, EnvironmentP environment);
    bool End_isAuthorized(IAsyncResult asyncResult);
    #endif
  }

  public class Client : IDisposable, Iface {
    public Client(TProtocol prot) : this(prot, prot)
    {
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;
    protected int seqid_;

    public TProtocol InputProtocol
    {
      get { return iprot_; }
    }
    public TProtocol OutputProtocol
    {
      get { return oprot_; }
    }


    #region " IDisposable Support "
    private bool _IsDisposed;

    // IDisposable
    public void Dispose()
    {
      Dispose(true);
    }
    

    protected virtual void Dispose(bool disposing)
    {
      if (!_IsDisposed)
      {
        if (disposing)
        {
          if (iprot_ != null)
          {
            ((IDisposable)iprot_).Dispose();
          }
          if (oprot_ != null)
          {
            ((IDisposable)oprot_).Dispose();
          }
        }
      }
      _IsDisposed = true;
    }
    #endregion


    
    #if SILVERLIGHT
    public IAsyncResult Begin_isAuthorized(AsyncCallback callback, object state, SubjectP subject, ObjectP object, ActionP action, EnvironmentP environment)
    {
      return send_isAuthorized(callback, state, subject, object, action, environment);
    }

    public bool End_isAuthorized(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_isAuthorized();
    }

    #endif

    public bool isAuthorized(SubjectP subject, ObjectP object, ActionP action, EnvironmentP environment)
    {
      #if !SILVERLIGHT
      send_isAuthorized(subject, object, action, environment);
      return recv_isAuthorized();

      #else
      var asyncResult = Begin_isAuthorized(null, null, subject, object, action, environment);
      return End_isAuthorized(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_isAuthorized(AsyncCallback callback, object state, SubjectP subject, ObjectP object, ActionP action, EnvironmentP environment)
    #else
    public void send_isAuthorized(SubjectP subject, ObjectP object, ActionP action, EnvironmentP environment)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("isAuthorized", TMessageType.Call, seqid_));
      isAuthorized_args args = new isAuthorized_args();
      args.Subject = subject;
      args.Object = object;
      args.Action = action;
      args.Environment = environment;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public bool recv_isAuthorized()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      isAuthorized_result result = new isAuthorized_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "isAuthorized failed: unknown result");
    }

  }
  public class Processor : TProcessor {
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_["isAuthorized"] = isAuthorized_Process;
    }

    protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
    private Iface iface_;
    protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

    public bool Process(TProtocol iprot, TProtocol oprot)
    {
      try
      {
        TMessage msg = iprot.ReadMessageBegin();
        ProcessFunction fn;
        processMap_.TryGetValue(msg.Name, out fn);
        if (fn == null) {
          TProtocolUtil.Skip(iprot, TType.Struct);
          iprot.ReadMessageEnd();
          TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
          oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
          x.Write(oprot);
          oprot.WriteMessageEnd();
          oprot.Transport.Flush();
          return true;
        }
        fn(msg.SeqID, iprot, oprot);
      }
      catch (IOException)
      {
        return false;
      }
      return true;
    }

    public void isAuthorized_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      isAuthorized_args args = new isAuthorized_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      isAuthorized_result result = new isAuthorized_result();
      result.Success = iface_.isAuthorized(args.Subject, args.Object, args.Action, args.Environment);
      oprot.WriteMessageBegin(new TMessage("isAuthorized", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class isAuthorized_args : TBase
  {
    private SubjectP _subject;
    private ObjectP _object;
    private ActionP _action;
    private EnvironmentP _environment;

    public SubjectP Subject
    {
      get
      {
        return _subject;
      }
      set
      {
        __isset.subject = true;
        this._subject = value;
      }
    }

    public ObjectP Object
    {
      get
      {
        return _object;
      }
      set
      {
        __isset.object = true;
        this._object = value;
      }
    }

    public ActionP Action
    {
      get
      {
        return _action;
      }
      set
      {
        __isset.action = true;
        this._action = value;
      }
    }

    public EnvironmentP Environment
    {
      get
      {
        return _environment;
      }
      set
      {
        __isset.environment = true;
        this._environment = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool subject;
      public bool object;
      public bool action;
      public bool environment;
    }

    public isAuthorized_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Subject = new SubjectP();
              Subject.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Object = new ObjectP();
              Object.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              Action = new ActionP();
              Action.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              Environment = new EnvironmentP();
              Environment.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("isAuthorized_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Subject != null && __isset.subject) {
        field.Name = "subject";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Subject.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Object != null && __isset.object) {
        field.Name = "object";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Object.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Action != null && __isset.action) {
        field.Name = "action";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        Action.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Environment != null && __isset.environment) {
        field.Name = "environment";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        Environment.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("isAuthorized_args(");
      bool __first = true;
      if (Subject != null && __isset.subject) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Subject: ");
        __sb.Append(Subject== null ? "<null>" : Subject.ToString());
      }
      if (Object != null && __isset.object) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Object: ");
        __sb.Append(Object== null ? "<null>" : Object.ToString());
      }
      if (Action != null && __isset.action) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Action: ");
        __sb.Append(Action== null ? "<null>" : Action.ToString());
      }
      if (Environment != null && __isset.environment) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Environment: ");
        __sb.Append(Environment== null ? "<null>" : Environment.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class isAuthorized_result : TBase
  {
    private bool _success;

    public bool Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public isAuthorized_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 0:
            if (field.Type == TType.Bool) {
              Success = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("isAuthorized_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.success) {
        field.Name = "Success";
        field.Type = TType.Bool;
        field.ID = 0;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Success);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("isAuthorized_result(");
      bool __first = true;
      if (__isset.success) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Success: ");
        __sb.Append(Success);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
