/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SubjectP : TBase
{
  private string _id;
  private List<AttributeValueP> _attributeValues;

  public string Id
  {
    get
    {
      return _id;
    }
    set
    {
      __isset.id = true;
      this._id = value;
    }
  }

  public List<AttributeValueP> AttributeValues
  {
    get
    {
      return _attributeValues;
    }
    set
    {
      __isset.attributeValues = true;
      this._attributeValues = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool id;
    public bool attributeValues;
  }

  public SubjectP() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            Id = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.List) {
            {
              AttributeValues = new List<AttributeValueP>();
              TList _list16 = iprot.ReadListBegin();
              for( int _i17 = 0; _i17 < _list16.Count; ++_i17)
              {
                AttributeValueP _elem18 = new AttributeValueP();
                _elem18 = new AttributeValueP();
                _elem18.Read(iprot);
                AttributeValues.Add(_elem18);
              }
              iprot.ReadListEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("SubjectP");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Id != null && __isset.id) {
      field.Name = "id";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Id);
      oprot.WriteFieldEnd();
    }
    if (AttributeValues != null && __isset.attributeValues) {
      field.Name = "attributeValues";
      field.Type = TType.List;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.Struct, AttributeValues.Count));
        foreach (AttributeValueP _iter19 in AttributeValues)
        {
          _iter19.Write(oprot);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("SubjectP(");
    bool __first = true;
    if (Id != null && __isset.id) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Id: ");
      __sb.Append(Id);
    }
    if (AttributeValues != null && __isset.attributeValues) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AttributeValues: ");
      __sb.Append(AttributeValues);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

