/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package puma.peputils.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2014-1-21")
public class ActionP implements org.apache.thrift.TBase<ActionP, ActionP._Fields>, java.io.Serializable, Cloneable, Comparable<ActionP> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ActionP");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ATTRIBUTE_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("attributeValues", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ActionPStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ActionPTupleSchemeFactory());
  }

  public String id; // required
  public List<AttributeValueP> attributeValues; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    ATTRIBUTE_VALUES((short)2, "attributeValues");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // ATTRIBUTE_VALUES
          return ATTRIBUTE_VALUES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ATTRIBUTE_VALUES, new org.apache.thrift.meta_data.FieldMetaData("attributeValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AttributeValueP.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ActionP.class, metaDataMap);
  }

  public ActionP() {
  }

  public ActionP(
    String id,
    List<AttributeValueP> attributeValues)
  {
    this();
    this.id = id;
    this.attributeValues = attributeValues;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ActionP(ActionP other) {
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetAttributeValues()) {
      List<AttributeValueP> __this__attributeValues = new ArrayList<AttributeValueP>(other.attributeValues.size());
      for (AttributeValueP other_element : other.attributeValues) {
        __this__attributeValues.add(new AttributeValueP(other_element));
      }
      this.attributeValues = __this__attributeValues;
    }
  }

  public ActionP deepCopy() {
    return new ActionP(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.attributeValues = null;
  }

  public String getId() {
    return this.id;
  }

  public ActionP setId(String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public int getAttributeValuesSize() {
    return (this.attributeValues == null) ? 0 : this.attributeValues.size();
  }

  public java.util.Iterator<AttributeValueP> getAttributeValuesIterator() {
    return (this.attributeValues == null) ? null : this.attributeValues.iterator();
  }

  public void addToAttributeValues(AttributeValueP elem) {
    if (this.attributeValues == null) {
      this.attributeValues = new ArrayList<AttributeValueP>();
    }
    this.attributeValues.add(elem);
  }

  public List<AttributeValueP> getAttributeValues() {
    return this.attributeValues;
  }

  public ActionP setAttributeValues(List<AttributeValueP> attributeValues) {
    this.attributeValues = attributeValues;
    return this;
  }

  public void unsetAttributeValues() {
    this.attributeValues = null;
  }

  /** Returns true if field attributeValues is set (has been assigned a value) and false otherwise */
  public boolean isSetAttributeValues() {
    return this.attributeValues != null;
  }

  public void setAttributeValuesIsSet(boolean value) {
    if (!value) {
      this.attributeValues = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((String)value);
      }
      break;

    case ATTRIBUTE_VALUES:
      if (value == null) {
        unsetAttributeValues();
      } else {
        setAttributeValues((List<AttributeValueP>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case ATTRIBUTE_VALUES:
      return getAttributeValues();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case ATTRIBUTE_VALUES:
      return isSetAttributeValues();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ActionP)
      return this.equals((ActionP)that);
    return false;
  }

  public boolean equals(ActionP that) {
    if (that == null)
      return false;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_attributeValues = true && this.isSetAttributeValues();
    boolean that_present_attributeValues = true && that.isSetAttributeValues();
    if (this_present_attributeValues || that_present_attributeValues) {
      if (!(this_present_attributeValues && that_present_attributeValues))
        return false;
      if (!this.attributeValues.equals(that.attributeValues))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_id = true && (isSetId());
    list.add(present_id);
    if (present_id)
      list.add(id);

    boolean present_attributeValues = true && (isSetAttributeValues());
    list.add(present_attributeValues);
    if (present_attributeValues)
      list.add(attributeValues);

    return list.hashCode();
  }

  @Override
  public int compareTo(ActionP other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAttributeValues()).compareTo(other.isSetAttributeValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttributeValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attributeValues, other.attributeValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ActionP(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("attributeValues:");
    if (this.attributeValues == null) {
      sb.append("null");
    } else {
      sb.append(this.attributeValues);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ActionPStandardSchemeFactory implements SchemeFactory {
    public ActionPStandardScheme getScheme() {
      return new ActionPStandardScheme();
    }
  }

  private static class ActionPStandardScheme extends StandardScheme<ActionP> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ActionP struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ATTRIBUTE_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list48 = iprot.readListBegin();
                struct.attributeValues = new ArrayList<AttributeValueP>(_list48.size);
                for (int _i49 = 0; _i49 < _list48.size; ++_i49)
                {
                  AttributeValueP _elem50;
                  _elem50 = new AttributeValueP();
                  _elem50.read(iprot);
                  struct.attributeValues.add(_elem50);
                }
                iprot.readListEnd();
              }
              struct.setAttributeValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ActionP struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.attributeValues != null) {
        oprot.writeFieldBegin(ATTRIBUTE_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.attributeValues.size()));
          for (AttributeValueP _iter51 : struct.attributeValues)
          {
            _iter51.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ActionPTupleSchemeFactory implements SchemeFactory {
    public ActionPTupleScheme getScheme() {
      return new ActionPTupleScheme();
    }
  }

  private static class ActionPTupleScheme extends TupleScheme<ActionP> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ActionP struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetAttributeValues()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetId()) {
        oprot.writeString(struct.id);
      }
      if (struct.isSetAttributeValues()) {
        {
          oprot.writeI32(struct.attributeValues.size());
          for (AttributeValueP _iter52 : struct.attributeValues)
          {
            _iter52.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ActionP struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.id = iprot.readString();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list53 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.attributeValues = new ArrayList<AttributeValueP>(_list53.size);
          for (int _i54 = 0; _i54 < _list53.size; ++_i54)
          {
            AttributeValueP _elem55;
            _elem55 = new AttributeValueP();
            _elem55.read(iprot);
            struct.attributeValues.add(_elem55);
          }
        }
        struct.setAttributeValuesIsSet(true);
      }
    }
  }

}

